# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBoqtady-FiBNEOIHinGgfdmim_duOzH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack
from sklearn.pipeline import Pipeline
import joblib

df=pd.read_csv('fake reviews dataset.csv')
df=df.rename(columns={'text_':'text'})
X=df.drop('label', axis=1)
Y=df['label']

x_train, x_test, y_train, y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y,
)

x_train

cat_pipe = Pipeline([
    ('vectorizer', TfidfVectorizer()),
])

num_pipe = Pipeline([
    ('scaler', StandardScaler()),
])

cat_pipe.fit(x_train['text'])
num_pipe.fit(x_train[['rating']])

encoder=OrdinalEncoder()
y_train=y_train.reset_index()

encoder.fit(y_train[['label']])
y_train_encoded = encoder.transform(y_train[['label']])

encoded_df=pd.DataFrame(y_train_encoded, columns=encoder.get_feature_names_out(['label']))
encoded_df
y_test=y_test.reset_index()
y_test_encoded=encoder.transform(y_test[['label']])

'''
df['text'].dtype
df['text']=df['text'].convert_dtypes()
df['text'].dtype
'''

vectorizer=TfidfVectorizer()
vectorizer.fit(x_train['text'])
x_train_vector=vectorizer.transform(x_train['text'])

scale=StandardScaler()
scale.fit(x_train[['rating']])
rating_scaled=scale.transform(x_train[['rating']])

x_train_final=hstack([x_train_vector, rating_scaled])
model = LogisticRegression(max_iter=2000, class_weight='balanced')
model.fit(x_train_final, encoded_df)

x_test_vector=vectorizer.transform(x_test['text'])
rating_scaled_test=scale.transform(x_test[['rating']])
x_test_final=hstack([x_test_vector, rating_scaled_test])

x_test_vec=vectorizer.transform(x_test['text'])
scores=cross_val_score(model, x_train_final, y_train_encoded)
scores
np.mean(scores)

#text=input('enter text')
#rating=int(input('enter rating'))
text = ["good bike, great suspension, comfortable"]
rating = 5

# 1. Vectorize text
text_vec=cat_pipe.transform(text)

# 2. Scale rating
rating_df = pd.DataFrame({"rating": [rating]})
rating_vec=num_pipe.transform(rating_df)

# 3. Combine
X_new = hstack([text_vec, rating_vec])

# 4. Predict
print(model.predict(X_new))
model.predict_proba(X_new)

joblib.dump(model, 'model.joblib')
joblib.dump(vectorizer, 'vectorizer.joblib')
joblib.dump(scale, 'scaler.joblib')